### ISSUE TITLE
comments from Rob Wilton: mega-range allocation

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#29]
via: https://datatracker.ietf.org/doc/draft-ietf-core-sid/ballot/

(4) The policy in 7.4.2 for allocation a SID mega-range seems to aiming this towards organizations rather than individuals.  The policy in 7.6 for the "IETF YANG SID Registry" requires an RFC.  What is the mechanism if an individual or open source project wanted to get SIDs assigned for some of their YANG modules?  I.e., should we be defining a separate mega-range, managed by IANA, with just Expert Review or Specification Required so that these modules could use SIDs allocated?  Or do you envisage a separate entity taking up the responsibility for coordinating this?

**Comment by cabo** [comment]
We said:

The mega-range concept means there can be more than one such entity.
https://comi.space is a proof of concept for how such an entity could operate.
I’d expect at least one of the organizations in the YANG ecosystem to pick this up and become such an entity.
Whether IANA also wants to be such an entity (beyond its role for IETF modules), I don’t know.
To demonstrate that we are entirely on the safe side, I’ve also written a PoC for a organization-less approach (leveraging IANA PENs):
https://datatracker.ietf.org/doc/draft-bormann-core-yang-sid-pen/
I’m not sure we want to pursue this; the advantage is a low-threshold (and low-disclosure!) way to get a sizable SID space; the disadvantage is that we would lose people who otherwise would have used services such as comi.space that make the registrations much more useful to the community.

**Comment by cabo** [comment]
Closed by Email response (no response to that yet, though).
