### ISSUE TITLE
comments from Eric Vynke: external organizations

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#33]
-- Section 7.5.2 --
AFAIK, many YANG modules are not originating at the IETF (Open Config, vendor specifics modules, ...). How can those non-IETF modules get a SID as the two ways to get a SID are based on RFC (if I understand correctly this section).

**Comment by cabo** [comment]
Duplicate of #29

**Comment by apelov** [comment]
Hi,

I feel strongly against adding any additional allocation policies without:
1) indicating what problem is it solving
2) how it fits in the current design objectives of COMI/SID/YANG-CBOR
3) why the currently described solutions would not work for it
4) how IANA would handle that

I think the goal of this design team should be to first and foremost answer the questions that arise through the reviews of the drafts at that stage. Adding new mechanisms should be a last resort in case the current solutions are not sufficient.

On that particular subject, the answer to Eric's comment is - other SDOs and companies can have their own Mega Range allocated, or use a third-party Mega Range Registry.

Alexander

**Comment by cabo** [comment]
On 2021-10-19, at 10:11, Alexander Pelov ***@***.***> wrote:
> 
> 
> Hi,
> 
> I feel strongly against adding any additional allocation policies without:

I’m leaning towards creating a separate document for the PEN-based allocation.
That will take it out of the fast path, and we can spend some thinking before making that mega-range allocation.

> 	• indicating what problem is it solving

1 µm threshold height

> 	• how it fits in the current design objectives of COMI/SID/YANG-CBOR

Perfectly.
It is not the allocation method of choice, but it is a great shortcut method.
The rest just works.

> 	• why the currently described solutions would not work for it

> 1 µm threshold height

> 	• how IANA would handle that

I don’t think this will lead to a surge in PEN allocations (PENs are currently designed into a lot of places).
IANA is not otherwise involved except for allocating those 100 000 mega-ranges.

> I think the goal of this design team should be to first and foremost answer the questions that arise through the reviews of the drafts at that stage. Adding new mechanisms should be a last resort in case the current solutions are not sufficient.

(i.e., a new document that can be discussed on its own timeline.)

> On that particular subject, the answer to Eric's comment is - other SDOs and companies can have their own Mega Range allocated, or use a third-party Mega Range Registry.

Yes.

Grüße, Carsten

**Comment by apelov** [comment]
Agreed that a second document may be the place to discuss other allocation methods.

I don't think we should have any mention of specific allocation methods in this document.

Cheers,
Alex

**Comment by cabo** [comment]
I agree.  However, a reply "this can all be handled via mega-ranges" is a little bloodless without some strawman way to use it, and both comi.space and this little drafts are such strawman approaches.  Would you prefer we don't mention them?

**Comment by mcr** [comment]
closed... new PEN allocation document written.
