### ISSUE TITLE
yang-cbor RW YANG meta-data RFC8791

### ISSUE THREAD

**Issue by mcr** [core-wg/yang-cbor#48]
2. As also raised by Ben, this document should probably cover the YANG data structure extension in RFC 8791.  This could potentially be done in addition to rc:yang-data, but perhaps better in its place.

**Comment by mcr** [comment]
When this document was first written, RFC8791 did not exist. That's why it does not address it.
I have no idea how/if to address this.

**Comment by abierman** [comment]
This issue is about the newer "structure" and "augment-structure" extensions in [RFC 8791](https://datatracker.ietf.org/doc/html/rfc8791)
[Sec 5](https://datatracker.ietf.org/doc/html/draft-ietf-core-yang-cbor#section-5) defines encoding for the "yang-data" extension from RFC 8040.
A similar section should be added for the new RFC.

The new RFC is a bit different. The name of structure actually defines a container.
In RFC 8040 the extension expects the top container to be the first child.
Other than that, it should be the same as for yang-data and augment.

**Comment by mcr** [comment]
closed, duplicated #28
