### ISSUE TITLE
How to support schema-mount with SIDs

### ISSUE THREAD

**Issue by abierman** [core-wg/yang-cbor#95]
[schema mount](https://www.rfc-editor.org/rfc/rfc8528.html) allows YANG modules to be rooted within another subtree

The data that is mounted and where it is mounted is configurable so it is not possible
to define global SIDs for these mounted nodes.

It is possible (and part of the standard) that an XPath or JSON instance-identifier can represent any mounted nodes.
This is possible because the full path-to-root is specified.

One possible solution is to support a Local SID megarange to allow the server to
create a local SID file specific to its own schema-mount configuration.

Example

     module A {
        container top {
           container myroot {
              yangmnt:mount-point "myroot";
          }
       }
    }
          
    module B {
        container top {
            leaf name { type string; }
        }
    }

If module B is mounted at mount-point "myroot" in module A  then the following nodes are added

    /A:top/myroot/B:top
    /A:top/myroot/B:top/name

There is no practical way to define global SIDs for mounted objects.
It may be possible for some standard mount-points like RFC 8530

**Comment by lemikev** [comment]
Hi Andy

The SID is never sufficient to identified a push object.
Push objects always need to be identified by an instance-identifier.

If we extend the definition of instance identifier to support schema-mount (on top of the single instance and multi instances data node already supported), I believe we are cover.

In the case of the previous example, 'top' container can be push using CoAP as follow:

POST example.com/c/ak/lg (Content-Format: application/cbor)
{
+1 : "Andy"      / SID 2401 /
}

This approach should cover all cases, schema mount is in array, schema mount within schema mount.
In YAND to CBOR, the enhanced  instance-identifier in should look as follow:

[[ <schema-mount-sid>, ... , <data-node-sid> ], <array-key>, ... ]

The consensus at one of the IETF meeting was to address schema-mount in a different draft.

Have a great weekend,
Michel

^^From: Andy Bierman ***@***.***>
Sent: 29 octobre 2021 12:01
To: core-wg/yang-cbor ***@***.***>
Cc: Michel Veillette ***@***.***>; Comment ***@***.***>
Subject: Re: [core-wg/yang-cbor] How to support schema-mount with SIDs (Issue #95)


External Email: Please use caution when opening links and attachments / Courriel externe: Soyez prudent avec les liens et documents joints

The URL from a GET request does not help.
If SID 200 is /foo/bar/baz then that is what the parser will decode.
The mount-point may be nested within the retrieved or pushed resource.
There must be a SID for the mounted object

/B:top/name and /A:/top/myroot/B:top/name can both appear in the same server.
The SID mapping cannot be conditional based on the unknown request URL.

-
You are receiving this because you commented.
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fcore-wg%2Fyang-cbor%2Fissues%2F95%23issuecomment-954860092&data=04%7C01%7CMichel.Veillette%40trilliant.com%7Cb1690e27387a423c972d08d99af53e55%7C4f6fbd130dfb415085c3d43260c04309%7C0%7C0%7C637711200416657845%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=HRTi5Z7eIZDO0ZscQpJNwnKd8KRCqcClelA1MM9a1bg%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADZVLN3YLMVWDVRHVIHA473UJLAKFANCNFSM5G5RFNSQ&data=04%7C01%7CMichel.Veillette%40trilliant.com%7Cb1690e27387a423c972d08d99af53e55%7C4f6fbd130dfb415085c3d43260c04309%7C0%7C0%7C637711200416667839%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=iCJDuffy3Wp9mKkyF5OIuSxSWjwCpXFiYOh25wqiytE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7CMichel.Veillette%40trilliant.com%7Cb1690e27387a423c972d08d99af53e55%7C4f6fbd130dfb415085c3d43260c04309%7C0%7C0%7C637711200416677833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=0Bg3A%2B3VrSrwnIC8HLSUn%2BipGy1m0fwTV%2BYiZnlymwE%3D&reserved=0> or Android<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7CMichel.Veillette%40trilliant.com%7Cb1690e27387a423c972d08d99af53e55%7C4f6fbd130dfb415085c3d43260c04309%7C0%7C0%7C637711200416677833%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=55K%2F95GRvR%2FWcu4eAlYNG%2FWENuuxRXudlXlJKEspftM%3D&reserved=0>.

**Comment by abierman** [comment]
YANG Push has a format already that is hierarchical.
It actually has 2 formats: a plain push and a patch format.
The problem is easily solved by defining SID to path mappings for the mounted objects.
Not interested in any design where a SID to Schema Node mapping yields conditional results.

**Comment by abierman** [comment]
RFC 8528 is a new and very complex way to define additional schema nodes.
These are not treated as the same schema node in multiple places.
A mount point is just like a regular container except the compiler has no way of knowing what child nodes are allowed for ANY implementation, and the child nodes can be different on EVERY implementation.

**Comment by abierman** [comment]
The consensus at one of the IETF meeting was to address schema-mount in a different draft.

No problem with that.
A vendor can use their range however they want, and publish the relevant mounted objects.
There are no changes needed.

**Comment by lemikev** [comment]
About Carsten comment above

> We not only need to have instance identifiers for the mounted nodes, but we need to be able to address them in the representation of a data node.  How would that work with paths of SIDs?
> 
> Of course we could do something like:
> 
> {
>   [1700, 2400]: …
> }

This is already the case for FETCH and iPATCH in the case of a multi-instance data node.

See examples
[1533, "eth0"]
in https://datatracker.ietf.org/doc/html/draft-ietf-core-comi-11#section-4.2.4.1

See examples
[1756, "tac.nrc.ca"] : null
in https://datatracker.ietf.org/doc/html/draft-ietf-core-comi-11#section-4.3.4.1

The propose extension to the instance-identifier just enhance this existing concept.
[[ <schema-mount-sid>, ... ], <data-node-sid> , <array-key>, ... ]

Assuming that SID 1700 is the schema-mount, the result however will be:
{
  [[1700], 2400]: …
}

If this schema-mount is an array, the result will be something like:

{
  [[1700], 2400, "eth0"]: …
}

**Comment by abierman** [comment]
It is not a matter of data instances.
The same YANG definition is used to create new schema nodes.
Think of it as a compile-time "augment" where the augment target is specified by
metadata (mount-point label). 
The modules that can be mounted at a given label are not in scope; not part of YANG at all.
The actual mappings are an implementation decision reported to the client in monitoring data at runtime.
The same YANG definition can be used to generate many different schema nodes.
This is no different that the "grouping" and "uses" already in YANG.

The yang-instance array contains YANG key values, so an instance of a schema node can be identified.
There are not ALSO different instances of a schema node. 

This issue should probably be put in a "next document" status.
The NETMOD WG should discuss the functional requirements

**Comment by lemikev** [comment]
Grouping definitively "create new schema nodes."
Each time a grouping is used, new SIDs are allocated.

For the schema mount, the same schema nodes can be positioned at different location in the schema tree.

For example, if I have a schema modeling a light, a luminaire can be modeled as a ARRAY OF light schema.
- Assuming the SID associated to the lights ARRAY in the luminaire schema is 2000
- Assuming the SID associated to the light status in the light schema is 3000
- The instance-identifier of the light status of the second light of the luminaire will be [[2000], 3000, 2]

This instance-identifier can be used in any context or method (GET, PUT, POST, FETCH, iPATCH) where a specific data node need to be referenced. Nothing else need to be enhanced to support schema mount.

**Comment by abierman** [comment]
schema mount can be nested. [3.4](https://datatracker.ietf.org/doc/html/rfc8528#section-3.4)

A solution for CoMI is one thing. Maybe what you suggest will work for CoMI.
I am interested in the YANG to CBOR encoding.
The current drafts fully support schema mount but the tools do not automatically generate the SIDs
for such objects.

The RFC treats the mounted nodes as a new node with a new path.
See the way [NACM](https://datatracker.ietf.org/doc/html/rfc8528#section-7) is handled for mounted objects.

This is not an issue for names as keys, only SIDs as keys.

Suppose you replace the SID key with an array e.g.  [root1, root2, node] 

       Real assigned SIDs:
       /top/foo/root  2012
       /bar/root2  3042     
       /some/node  4027  

       /top/foo/root/bar/root2/some/node   [2012, 3042, 4027]


The decoder has to start with the first entry (the real root), then splice the
path from root to root2 to the end of string, then splice the path from root to node to the end of of the string.
Not sure how any of this would work with delta-SID, bit it is too complex.


The XPath approach is to assign a SID to this path and not treat the mount-points in any special way.
IMO a better approach for implementation simplicity and efficiency.
Much easier to always have one Integer SID as key, and not an array of SIDs

**Comment by lemikev** [comment]
To show how it works, let take the second example in https://datatracker.ietf.org/doc/html/draft-ietf-core-comi-11#section-4.2.3.1. This example is currently is as follow:

  REQ: GET </c/a5>

  RES: 2.05 Content (Content-Format: application/yang-data+cbor; id=sid)
  {
    1721 : {
      2 : "2014-10-26T12:16:51Z",    / current-datetime (SID 1723) /
      1 : "2014-10-21T03:00:00Z"     / boot-datetime (SID 1722) /
    }
  }

Let assume this container is now part of a schema mount assigned to SID 1250.
This schema mount can be retrieved with a GET SID 1250 as follow:

REQ: GET </c/Ti>

RES: 2.05 Content (Content-Format: application/yang-data+cbor)
{
  1250 : {
    471 : {                          / SID 1721 /
      2 : "2014-10-26T12:16:51Z",    / current-datetime (SID 1723) /
      1 : "2014-10-21T03:00:00Z"     / boot-datetime (SID 1722) /
    }
  }
}

The current-datetime within this specific schema mount can be retrieved with a GET as follow:

REQ: GET </c/Ti/a7>

RES: 2.05 Content (Content-Format: application/yang-data+cbor)
"2014-10-26T12:16:51Z"
